version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "${PORT_GATEWAY}:${PORT_GATEWAY}"
    environment:
      - PORT=3000
      - PATIENT_SERVICE_URL=https://smart-healthcare-lckn.onrender.com
      - DOCTOR_SERVICE_URL=https://smart-healthcare-doctor-service.onrender.com
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3003
      - TELEMEDICINE_SERVICE_URL=http://telemedicine-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
      - AI_SERVICE_URL=https://smart-healthcare-1-morq.onrender.com
      - JWT_SECRET=smarthealthcare_supersecret_key
    depends_on:
      - patient-service
      - doctor-service
      - appointment-service

  patient-service:
    build: ./patient-service
    ports:
      - "${PORT_PATIENT}:${PORT_PATIENT}"
    environment:
      - PORT=${PORT_PATIENT}
      - MONGO_URI=${MONGO_URI_BASE}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  doctor-service:
    build: ./doctor-service
    ports:
      - "${PORT_DOCTOR}:${PORT_DOCTOR}"
    environment:
      - PORT=${PORT_DOCTOR}
      - MONGO_URI=${MONGO_URI_BASE}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  appointment-service:
    build: ./appointment-service
    ports:
      - "${PORT_APPOINTMENT}:${PORT_APPOINTMENT}"
    environment:
      - PORT=${PORT_APPOINTMENT}
      - MONGO_URI=${MONGO_URI_BASE}

  telemedicine-service:
    build: ./telemedicine-service
    ports:
      - "${PORT_TELEMEDICINE}:${PORT_TELEMEDICINE}"
    environment:
      - PORT=3004
      - MONGO_URI=mongodb+srv://lpasindu30_db_user:SdSjcC0yYyX1JIwj@cluster0.gvxgnvm.mongodb.net/?appName=Cluster0
      - AGORA_APP_ID=ebd1cd2c36ac4a3394dc797349935d6f
      - AGORA_APP_CERTIFICATE=45a454bb8c02433d91ad726c6e2c71c7
      - AGORA_TOKEN_EXPIRY_SECONDS=3600

  payment-service:
    build: ./payment-service
    ports:
      - "${PORT_PAYMENT}:${PORT_PAYMENT}"
    environment:
      - PORT=3005
      - PAYHERE_MERCHANT_ID=1234712
      - PAYHERE_MERCHANT_SECRET=MTg4NDA5NTM2ODI4NDIyOTk4NjgxNjkyODY4MTYxMjgwNzUxNjY2Mg==
      - FRONTEND_BASE_URL=https://smarthealthcar.me
      - PAYHERE_RETURN_BASE_URL=https://smarthealthcar.me
      - PAYHERE_NOTIFY_URL=https://smart-healthcare-payment.onrender.com/payhere/notify

  notification-service:
    build: ./notification-service
    ports:
      - "${PORT_NOTIFICATION}:${PORT_NOTIFICATION}"
    environment:
      - PORT=${PORT_NOTIFICATION}

  ai-service:
    build: ./ai-service
    ports:
      - "${PORT_AI}:${PORT_AI}"
    environment:
      - PORT=3007
      - MONGO_URI=mongodb+srv://lpasindu30_db_user:SdSjcC0yYyX1JIwj@cluster0.gvxgnvm.mongodb.net/smart-health-ai?appName=Cluster0
      - GEMINI_API_KEY=AIzaSyBVihJ6P8G457ueV77ip-3xtsCeXGvibUo
      - GROQ_API_KEY=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
